version: '2'
services:
  dns:
    restart: always
    build:
        context: .
    volumes:
      - ./config/dnsmasq.conf:/etc/dnsmasq.conf
      - ./config/dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
